### ISSUE TITLE
JUnit 4->5 migration should handle Assert.assertThat()

### ISSUE THREAD

**Issue by sambsnyd** [openrewrite/rewrite-testing-frameworks#29] opened 2021-01-06 19:37 UTC
JUnit 4's `Assert` class has two deprecated overloads of the method `assertThat` which accept Hamcrest matchers.
These methods, and Hamcrest matchers, do not exist as part of JUnit 5. 

As part of the 4->5 migration any usage of these methods should be replaced with `org.hamcrest.MatcherAssert.assertThat()` and a dependency on the stand-alone Hamcrest library should be added to the pom.

**Comment by traceyyoshima** [comment] 2021-04-02 19:44
Note: I didn't sweep through both classes exhaustively, but I noticed there are other instances that exist in the Assert class that don't exist in the Assertions class.
It seems reasonable to translate the missing asserts to an equivalent if it's missing.

**Comment by tkvangorder** [comment] 2021-06-10 21:11
Duplicate of #63

**Closed by tkvangorder** 2021-06-10 21:11 UTC
Labels: enhancement
