### ISSUE TITLE
Execution fails due to InvalidPathException trying to open a maven group/artifact ID as a file

### ISSUE THREAD

**Issue by aarner42** [openrewrite/rewrite-testing-frameworks#248] opened 2022-08-18 15:38 UTC
Trying to use the rewrite-test-framework recipes to migrate a project from Junit4 to Junit5, receive the following exception:

Caused by: java.nio.file.InvalidPathException: **Illegal char <:> at index 10: org.apache:apache\pom.xml**
    at sun.nio.fs.WindowsPathParser.normalize (WindowsPathParser.java:182)
    at sun.nio.fs.WindowsPathParser.parse (WindowsPathParser.java:153)
    at sun.nio.fs.WindowsPathParser.parse (WindowsPathParser.java:77)
    at sun.nio.fs.WindowsPath.parse (WindowsPath.java:92)
    at sun.nio.fs.WindowsFileSystem.getPath (WindowsFileSystem.java:232)
    at java.nio.file.Path.of (Path.java:147)
    at java.nio.file.Paths.get (Paths.java:69)
    at org.openrewrite.maven.internal.MavenPomDownloader.download (MavenPomDownloader.java:218)
    at org.openrewrite.maven.tree.ResolvedPom$Resolver.resolveParentPropertiesAndRepositoriesRecursively (ResolvedPom.java:351)
    at org.openrewrite.maven.tree.ResolvedPom$Resolver.resolveParentPropertiesAndRepositoriesRecursively (ResolvedPom.java:362)
    at org.openrewrite.maven.tree.ResolvedPom$Resolver.resolveParentsRecursively (ResolvedPom.java:308)
    at org.openrewrite.maven.tree.ResolvedPom.resolveDependencies (ResolvedPom.java:569)
    at org.openrewrite.maven.tree.ResolvedPom.resolveDependencies (ResolvedPom.java:499)
    at org.openrewrite.maven.tree.MavenResolutionResult.resolveDependencies (MavenResolutionResult.java:159)
    at org.openrewrite.maven.MavenParser.parseInputs (MavenParser.java:111)
    at org.openrewrite.Parser.parse (Parser.java:39)
    at org.openrewrite.maven.MavenMojoProjectParser.parseMaven (MavenMojoProjectParser.java:302)
    at org.openrewrite.maven.MavenMojoProjectParser.listSourceFiles (MavenMojoProjectParser.java:115)
    at org.openrewrite.maven.AbstractRewriteMojo.listResults (AbstractRewriteMojo.java:210)
    at org.openrewrite.maven.AbstractRewriteRunMojo.execute (AbstractRewriteRunMojo.java:48)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)

running on Windows 10, JDK 17 (Temurin).  Attaching the full
build log with debug enabled, and the chain of POMs that exhibit the issue.  (root -> services -> portal-services)

[mavenBuildLog.txt](https://github.com/openrewrite/rewrite-testing-frameworks/files/9375268/mavenBuildLog.txt)

[root-pom.xml.txt](https://github.com/openrewrite/rewrite-testing-frameworks/files/9375252/root-pom.xml.txt)
[services-pom.xml.txt](https://github.com/openrewrite/rewrite-testing-frameworks/files/9375254/services-pom.xml.txt)
[portal-services.pom.xml.txt](https://github.com/openrewrite/rewrite-testing-frameworks/files/9375256/portal-services.pom.xml.txt)

**Comment by pway99** [comment] 2022-08-24 19:40
Hi @aarner42,  It's difficult to fully understand the problem from the stack trace.  I had to remove a lot from the sample poms to create something that would build and was not able to reproduce this error.  Can you perhaps provide a small sample project we can use to investigate?

**Comment by tkvangorder** [comment] 2022-08-29 22:25
@pway99 I wonder if this is related to this fix that we fixed two weeks ago?

https://github.com/openrewrite/rewrite/commit/92a5be3ffe06cd66099c336b232416fd93a78e49

**Comment by pway99** [comment] 2022-08-29 23:02
@tkvangorder that's a good question, I was not able to reproduce the error.

**Comment by tkvangorder** [comment] 2022-09-01 18:02
I think this is likely fixed in the upcoming release. @aarner42 , we are expecting to do a release in the next couple of days.

**Closed by tkvangorder** 2022-09-01 18:02 UTC
Labels: question

**Comment by aarner42** [comment] 2022-10-11 07:50
Sorry for the late reply, I was on PTO on a cycling trip for the past
several days.  I'll keep an eye out for the next release and retry the
script on our build.  Hopefully that fixed the issue, if not I'll work on a
more suitable reproducer for the issue that doesn't require our whole
proprietary build environment.

Thanks for the updates,
-a
